### ISSUE TITLE
Add back and next button for each react components

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/react-dds-courses#7]

**Comment by junquera** [comment]
Hi! I really like the project! I want to do this, but I'm not pretty sure what do you want. Do you mean a button in each component for "scrolling" to the previous/next?

**Comment by rizafahmi** [comment]
For now just simply emulate back/forward button on the browser. Use `react-router-dom` with `goBack()` or something like that @junquera :)

**Comment by ka3work** [comment]
@rizafahmi Can I try to work on this one?

**Comment by rizafahmi** [comment]
Sure, it's yours :)
